### ISSUE TITLE
Move reso-certification/server/services/etl into its Own Package

### ISSUE THREAD

**Issue by mohit-s96** [RESOStandards/reso-certification-etl#6]
Refer [#968](https://github.com/RESOStandards/reso-certification/issues/968)

The migration is complete in [#1113](https://github.com/RESOStandards/reso-certification/pull/1113) (failing CI) and a few minor problems in ETL have been fixed in #5. The migration was not 100% successful as 2 tests were failing (related to standard value counts cc: @darnjo ).

 Check the failing tests [here](https://github.com/RESOStandards/reso-certification/runs/7748719612?check_suite_focus=true)

**Comment by darnjo** [comment]
Separating this issue from the migration of the ETL code.

**Comment by darnjo** [comment]
This is related to #4. Part of this was done previously but was out of date, and needed to be caught up with the current code from the Cert API. This can be closed with #5.

**Comment by mohit-s96** [comment]
This ticket is outdated. Closing it for now.
